AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SSM RunCommand

Parameters:
  instanceid:
    Type: String

Resources:
  FunctionIamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "logs:CreateLogGroup"
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
          - Effect: Allow
            Action:
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/function-ssm-runcommand-${AWS::Region}:*"
          - Effect: Allow
            Action:
              - "ssm:SendCommand"
            Resource: "*"
      ManagedPolicyName: !Sub "policy-lambda-ssm-runcommand-${AWS::Region}"

  FunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - !Ref FunctionIamPolicy
      RoleName: !Sub "role-lambda-ssm-runcommand-${AWS::Region}"
      Tags:
        - Key: Name
          Value: !Sub "role-lambda-ssm-runcommand-${AWS::Region}"

  S3:
    Type: AWS::S3::Bucket
    DependsOn: Function
    Properties:
      BucketName: !Sub s3-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt Function.Arn

  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Environment:
        Variables:
          instance_id: !Ref instanceid
      Events:
        S3:
          Properties:
            Bucket: !Ref S3
            Events: s3:ObjectCreated:*
          Type: S3
      FunctionName: !Sub function-ssm-runcommand-${AWS::Region}
      Handler: lambda_function.lambda_handler
      Role: !GetAtt FunctionIamRole.Arn
      Runtime: python3.9
      Timeout: 900